// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models_generated

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/diggerhq/digger/next/model"
)

func newProject(db *gorm.DB, opts ...gen.DOOption) project {
	_project := project{}

	_project.projectDo.UseDB(db, opts...)
	_project.projectDo.UseModel(&model.Project{})

	tableName := _project.projectDo.TableName()
	_project.ALL = field.NewAsterisk(tableName)
	_project.ID = field.NewString(tableName, "id")
	_project.Name = field.NewString(tableName, "name")
	_project.CreatedAt = field.NewTime(tableName, "created_at")
	_project.UpdatedAt = field.NewTime(tableName, "updated_at")
	_project.OrganizationID = field.NewString(tableName, "organization_id")
	_project.TeamID = field.NewInt64(tableName, "team_id")
	_project.ProjectStatus = field.NewString(tableName, "project_status")
	_project.Slug = field.NewString(tableName, "slug")
	_project.LatestActionOn = field.NewString(tableName, "latest_action_on")
	_project.RepoID = field.NewInt64(tableName, "repo_id")
	_project.ConfigurationYaml = field.NewString(tableName, "configuration_yaml")
	_project.Status = field.NewString(tableName, "status")
	_project.IsGenerated = field.NewBool(tableName, "is_generated")
	_project.IsInMainBranch = field.NewBool(tableName, "is_in_main_branch")
	_project.DeletedAt = field.NewField(tableName, "deleted_at")
	_project.TerraformWorkingDir = field.NewString(tableName, "terraform_working_dir")
	_project.IsManagingState = field.NewBool(tableName, "is_managing_state")
	_project.Labels = field.NewString(tableName, "labels")
	_project.IsDriftDetectionEnabled = field.NewBool(tableName, "is_drift_detection_enabled")
	_project.DriftCrontab = field.NewString(tableName, "drift_crontab")
	_project.Branch = field.NewString(tableName, "branch")
	_project.LatestDriftOutput = field.NewString(tableName, "latest_drift_output")
	_project.IacType = field.NewString(tableName, "iac_type")
	_project.Workspace = field.NewString(tableName, "workspace")
	_project.WorkflowFile = field.NewString(tableName, "workflow_file")
	_project.IncludePatterns = field.NewString(tableName, "include_patterns")
	_project.AutoApprove = field.NewBool(tableName, "auto_approve")
	_project.ExcludePatterns = field.NewString(tableName, "exclude_patterns")
	_project.Workflow = field.NewString(tableName, "workflow")

	_project.fillFieldMap()

	return _project
}

type project struct {
	projectDo

	ALL                     field.Asterisk
	ID                      field.String
	Name                    field.String
	CreatedAt               field.Time
	UpdatedAt               field.Time
	OrganizationID          field.String
	TeamID                  field.Int64
	ProjectStatus           field.String
	Slug                    field.String
	LatestActionOn          field.String
	RepoID                  field.Int64
	ConfigurationYaml       field.String
	Status                  field.String
	IsGenerated             field.Bool
	IsInMainBranch          field.Bool
	DeletedAt               field.Field
	TerraformWorkingDir     field.String
	IsManagingState         field.Bool
	Labels                  field.String
	IsDriftDetectionEnabled field.Bool
	DriftCrontab            field.String
	Branch                  field.String
	LatestDriftOutput       field.String
	IacType                 field.String
	Workspace               field.String
	WorkflowFile            field.String
	IncludePatterns         field.String
	AutoApprove             field.Bool
	ExcludePatterns         field.String
	Workflow                field.String

	fieldMap map[string]field.Expr
}

func (p project) Table(newTableName string) *project {
	p.projectDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p project) As(alias string) *project {
	p.projectDo.DO = *(p.projectDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *project) updateTableName(table string) *project {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.Name = field.NewString(table, "name")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.OrganizationID = field.NewString(table, "organization_id")
	p.TeamID = field.NewInt64(table, "team_id")
	p.ProjectStatus = field.NewString(table, "project_status")
	p.Slug = field.NewString(table, "slug")
	p.LatestActionOn = field.NewString(table, "latest_action_on")
	p.RepoID = field.NewInt64(table, "repo_id")
	p.ConfigurationYaml = field.NewString(table, "configuration_yaml")
	p.Status = field.NewString(table, "status")
	p.IsGenerated = field.NewBool(table, "is_generated")
	p.IsInMainBranch = field.NewBool(table, "is_in_main_branch")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.TerraformWorkingDir = field.NewString(table, "terraform_working_dir")
	p.IsManagingState = field.NewBool(table, "is_managing_state")
	p.Labels = field.NewString(table, "labels")
	p.IsDriftDetectionEnabled = field.NewBool(table, "is_drift_detection_enabled")
	p.DriftCrontab = field.NewString(table, "drift_crontab")
	p.Branch = field.NewString(table, "branch")
	p.LatestDriftOutput = field.NewString(table, "latest_drift_output")
	p.IacType = field.NewString(table, "iac_type")
	p.Workspace = field.NewString(table, "workspace")
	p.WorkflowFile = field.NewString(table, "workflow_file")
	p.IncludePatterns = field.NewString(table, "include_patterns")
	p.AutoApprove = field.NewBool(table, "auto_approve")
	p.ExcludePatterns = field.NewString(table, "exclude_patterns")
	p.Workflow = field.NewString(table, "workflow")

	p.fillFieldMap()

	return p
}

func (p *project) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *project) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 29)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["organization_id"] = p.OrganizationID
	p.fieldMap["team_id"] = p.TeamID
	p.fieldMap["project_status"] = p.ProjectStatus
	p.fieldMap["slug"] = p.Slug
	p.fieldMap["latest_action_on"] = p.LatestActionOn
	p.fieldMap["repo_id"] = p.RepoID
	p.fieldMap["configuration_yaml"] = p.ConfigurationYaml
	p.fieldMap["status"] = p.Status
	p.fieldMap["is_generated"] = p.IsGenerated
	p.fieldMap["is_in_main_branch"] = p.IsInMainBranch
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["terraform_working_dir"] = p.TerraformWorkingDir
	p.fieldMap["is_managing_state"] = p.IsManagingState
	p.fieldMap["labels"] = p.Labels
	p.fieldMap["is_drift_detection_enabled"] = p.IsDriftDetectionEnabled
	p.fieldMap["drift_crontab"] = p.DriftCrontab
	p.fieldMap["branch"] = p.Branch
	p.fieldMap["latest_drift_output"] = p.LatestDriftOutput
	p.fieldMap["iac_type"] = p.IacType
	p.fieldMap["workspace"] = p.Workspace
	p.fieldMap["workflow_file"] = p.WorkflowFile
	p.fieldMap["include_patterns"] = p.IncludePatterns
	p.fieldMap["auto_approve"] = p.AutoApprove
	p.fieldMap["exclude_patterns"] = p.ExcludePatterns
	p.fieldMap["workflow"] = p.Workflow
}

func (p project) clone(db *gorm.DB) project {
	p.projectDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p project) replaceDB(db *gorm.DB) project {
	p.projectDo.ReplaceDB(db)
	return p
}

type projectDo struct{ gen.DO }

type IProjectDo interface {
	gen.SubQuery
	Debug() IProjectDo
	WithContext(ctx context.Context) IProjectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectDo
	WriteDB() IProjectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectDo
	Not(conds ...gen.Condition) IProjectDo
	Or(conds ...gen.Condition) IProjectDo
	Select(conds ...field.Expr) IProjectDo
	Where(conds ...gen.Condition) IProjectDo
	Order(conds ...field.Expr) IProjectDo
	Distinct(cols ...field.Expr) IProjectDo
	Omit(cols ...field.Expr) IProjectDo
	Join(table schema.Tabler, on ...field.Expr) IProjectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectDo
	Group(cols ...field.Expr) IProjectDo
	Having(conds ...gen.Condition) IProjectDo
	Limit(limit int) IProjectDo
	Offset(offset int) IProjectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectDo
	Unscoped() IProjectDo
	Create(values ...*model.Project) error
	CreateInBatches(values []*model.Project, batchSize int) error
	Save(values ...*model.Project) error
	First() (*model.Project, error)
	Take() (*model.Project, error)
	Last() (*model.Project, error)
	Find() ([]*model.Project, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Project, err error)
	FindInBatches(result *[]*model.Project, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Project) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectDo
	Assign(attrs ...field.AssignExpr) IProjectDo
	Joins(fields ...field.RelationField) IProjectDo
	Preload(fields ...field.RelationField) IProjectDo
	FirstOrInit() (*model.Project, error)
	FirstOrCreate() (*model.Project, error)
	FindByPage(offset int, limit int) (result []*model.Project, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectDo) Debug() IProjectDo {
	return p.withDO(p.DO.Debug())
}

func (p projectDo) WithContext(ctx context.Context) IProjectDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectDo) ReadDB() IProjectDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectDo) WriteDB() IProjectDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectDo) Session(config *gorm.Session) IProjectDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectDo) Clauses(conds ...clause.Expression) IProjectDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectDo) Returning(value interface{}, columns ...string) IProjectDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectDo) Not(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectDo) Or(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectDo) Select(conds ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectDo) Where(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectDo) Order(conds ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectDo) Distinct(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectDo) Omit(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectDo) Join(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectDo) Group(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectDo) Having(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectDo) Limit(limit int) IProjectDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectDo) Offset(offset int) IProjectDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectDo) Unscoped() IProjectDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectDo) Create(values ...*model.Project) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectDo) CreateInBatches(values []*model.Project, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectDo) Save(values ...*model.Project) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectDo) First() (*model.Project, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Project), nil
	}
}

func (p projectDo) Take() (*model.Project, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Project), nil
	}
}

func (p projectDo) Last() (*model.Project, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Project), nil
	}
}

func (p projectDo) Find() ([]*model.Project, error) {
	result, err := p.DO.Find()
	return result.([]*model.Project), err
}

func (p projectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Project, err error) {
	buf := make([]*model.Project, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectDo) FindInBatches(result *[]*model.Project, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectDo) Attrs(attrs ...field.AssignExpr) IProjectDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectDo) Assign(attrs ...field.AssignExpr) IProjectDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectDo) Joins(fields ...field.RelationField) IProjectDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectDo) Preload(fields ...field.RelationField) IProjectDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectDo) FirstOrInit() (*model.Project, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Project), nil
	}
}

func (p projectDo) FirstOrCreate() (*model.Project, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Project), nil
	}
}

func (p projectDo) FindByPage(offset int, limit int) (result []*model.Project, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectDo) Delete(models ...*model.Project) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectDo) withDO(do gen.Dao) *projectDo {
	p.DO = *do.(*gen.DO)
	return p
}
