{{- if not .Values.ui.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taco-ui.fullname" . }}-secret
  labels:
    {{- include "taco-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  # WorkOS configuration
  {{- if .Values.ui.env.workos.redirectUri }}
  WORKOS_REDIRECT_URI: {{ .Values.ui.env.workos.redirectUri | quote }}
  {{- end }}
  {{- if .Values.ui.env.workos.apiKey }}
  WORKOS_API_KEY: {{ .Values.ui.env.workos.apiKey | quote }}
  {{- end }}
  {{- if .Values.ui.env.workos.clientId }}
  WORKOS_CLIENT_ID: {{ .Values.ui.env.workos.clientId | quote }}
  {{- end }}
  {{- if .Values.ui.env.workos.cookiePassword }}
  WORKOS_COOKIE_PASSWORD: {{ .Values.ui.env.workos.cookiePassword | quote }}
  {{- end }}
  {{- if .Values.ui.env.workos.webhookSecret }}
  WORKOS_WEBHOOK_SECRET: {{ .Values.ui.env.workos.webhookSecret | quote }}
  {{- end }}
  
  # Backend service URLs
  {{- if .Values.ui.env.backends.orchestratorUrl }}
  ORCHESTRATOR_BACKEND_URL: {{ .Values.ui.env.backends.orchestratorUrl | quote }}
  {{- end }}
  {{- if .Values.ui.env.backends.orchestratorSecret }}
  ORCHESTRATOR_BACKEND_SECRET: {{ .Values.ui.env.backends.orchestratorSecret | quote }}
  {{- end }}
  {{- if .Values.ui.env.backends.driftReportingUrl }}
  DRIFT_REPORTING_BACKEND_URL: {{ .Values.ui.env.backends.driftReportingUrl | quote }}
  {{- end }}
  {{- if .Values.ui.env.backends.driftReportingWebhookSecret }}
  DRIFT_REPORTING_BACKEND_WEBHOOK_SECRET: {{ .Values.ui.env.backends.driftReportingWebhookSecret | quote }}
  {{- end }}
  {{- if .Values.ui.env.backends.statesmanUrl }}
  STATESMAN_BACKEND_URL: {{ .Values.ui.env.backends.statesmanUrl | quote }}
  {{- end }}
  {{- if .Values.ui.env.backends.statesmanWebhookSecret }}
  STATESMAN_BACKEND_WEBHOOK_SECRET: {{ .Values.ui.env.backends.statesmanWebhookSecret | quote }}
  {{- end }}
{{- end }}

