{{- if and .Values.postgresql.enabled .Values.postgresql.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.credentials.orchestrator.secretName }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.credentials.orchestrator.username | quote }}
  password: {{ .Values.postgresql.credentials.orchestrator.password | quote }}
  postgres-password: {{ .Values.postgresql.credentials.orchestrator.password | quote }}
  database: {{ .Values.postgresql.credentials.orchestrator.database | quote }}
  host: {{ printf "%s-rw" .Values.postgresql.sharedCluster.name | quote }}
  port: "5432"
  sslmode: "disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.credentials.statesman.secretName }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.credentials.statesman.username | quote }}
  password: {{ .Values.postgresql.credentials.statesman.password | quote }}
  postgres-password: {{ .Values.postgresql.credentials.statesman.password | quote }}
  database: {{ .Values.postgresql.credentials.statesman.database | quote }}
  host: {{ printf "%s-rw" .Values.postgresql.sharedCluster.name | quote }}
  port: "5432"
  sslmode: "disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.credentials.token.secretName }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.credentials.token.username | quote }}
  password: {{ .Values.postgresql.credentials.token.password | quote }}
  postgres-password: {{ .Values.postgresql.credentials.token.password | quote }}
  database: {{ .Values.postgresql.credentials.token.database | quote }}
  host: {{ printf "%s-rw" .Values.postgresql.sharedCluster.name | quote }}
  port: "5432"
  sslmode: "disable"
{{- end }}
