{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opentaco-platform-reference.minio.fullname" . }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "opentaco-platform-reference.minio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opentaco-platform-reference.minio.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opentaco-platform-reference.minio.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "opentaco-platform-reference.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - :{{ .Values.minio.service.consolePort }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "opentaco-platform-reference.minio.fullname" . }}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "opentaco-platform-reference.minio.fullname" . }}
                  key: rootPassword
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
          volumeMounts:
            - name: data
              mountPath: /data
      {{- if not .Values.minio.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.minio.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}
        {{- if .Values.minio.persistence.storageClassName }}
        storageClassName: {{ .Values.minio.persistence.storageClassName }}
        {{- end }}
  {{- end }}
{{- end }}
