{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentaco-platform-reference.minio.fullname" . }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.minio.auth.rootUser | quote }}
  rootPassword: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}
