{{- $statesman := .Values.statesman | default dict -}}
{{- $obj := $statesman.objectStorageSecret | default dict -}}
{{- if and .Values.minio.enabled ($obj.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $obj.name }}
  labels:
    {{- include "opentaco-platform-reference.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
  OPENTACO_S3_BUCKET: {{ $obj.bucket | quote }}
  OPENTACO_S3_REGION: {{ $obj.region | quote }}
  AWS_ENDPOINT: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "opentaco-platform-reference.minio.fullname" .) .Release.Namespace .Values.minio.service.apiPort | quote }}
{{- if $obj.prefix }}
  OPENTACO_S3_PREFIX: {{ $obj.prefix | quote }}
{{- end }}
{{- if $obj.awsRegion }}
  AWS_REGION: {{ $obj.awsRegion | quote }}
{{- end }}
{{- end }}
