name: run-digger
description: Manage terraform collaboration
author: Digger

inputs:
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  setup-aws:
    description: Setup AWS
    required: false
    default: 'false'
  aws-access-key-id:
    description: AWS access key id
    required: false
  aws-secret-access-key:
    description: AWS secret access key
    required: false
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  setup-google-cloud:
    description: Setup google cloud
    required: false
    default: 'false'
  google-auth-credentials:
      description: Service account key used got Google auth (mutually exclusive with 'google-workload-identity-provider' input)
      required: false
  google-workload-identity-provider:
      description: Workload identity provider to be used for Google OIDC auth (mutually exclusive with 'google-auth-credentials' input)
      required: false
  google-service_account:
      description: Service account to be used when the 'google-workload-identity-provider' input is specified)
      required: false
  setup-terragrunt:
    description: Setup terragrunt
    required: false
    default: 'false'
  terragrunt-version:
    description: Terragrunt version
    required: false
    default: v0.45.4
  setup-terraform:
    description: Setup terraform
    required: false
    default: 'false'
  terraform-version:
    description: Terraform version
    required: false
    default: v1.4.5

outputs:
  output:
    value: ${{ steps.digger.outputs.output }}
    description: The terraform output

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      if: github.event_name == 'issue_comment'
      with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
    - uses: actions/checkout@v3
      if: github.event_name != 'issue_comment'

    - name: Validate General Input Configuration
      run: |
        if [[ "${{ inputs.setup-aws }}" == "false" && "${{ inputs.setup-google-cloud }}" == "false" ]]; then
          echo "Either 'setup-aws' or 'setup-google-cloud' input must be set to 'true'"
        elif [[ "${{ inputs.setup-terragrunt }}" == "false" && "${{ inputs.setup-terraform }}" == "false" ]]; then
          echo "Either 'setup-terragrunt' or 'setup-terraform' input must be set to 'true'"
        else
          exit 0
        fi
        exit 1
      shell: bash
      if: inputs.setup-google-cloud == 'true'

    - name: Validate Input Configuration for Google
      run: |
        if [[ -z "${{ inputs.google-auth-credentials }}" && -z "${{ inputs.google-workload-identity-provider }}" ]]; then
          echo "Either 'google-auth-credentials' or 'google-workload-identity-provider' input must be specified with 'setup-google-cloud'"
        elif [[ ! -z "${{ inputs.google-workload-identity-provider }}" && -z "${{ inputs.google-service_account }}" ]]; then
          echo "'google-service_account' input must be specified with 'google-workload-identity-provider'"
        else
          exit 0
        fi
        exit 1
      shell: bash
      if: inputs.setup-google-cloud == 'true'

    - name: Set up Google Auth Using A Service Account Key
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.google-auth-credentials }}
      if: ${{ inputs.setup-google-cloud == 'true' && inputs.google-auth-credentials != '' }}

    - name: Set up Google Auth Using Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        service_account: ${{ inputs.google-service_account }}
        workload_identity_provider: ${{ inputs.google-workload-identity-provider }}
      if: ${{ inputs.setup-google-cloud == 'true' && inputs.google-workload-identity-provider != '' }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      if: inputs.setup-google-cloud == 'true'

    - name: Configure Test AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
      if: inputs.setup-aws == 'true'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}
      if: inputs.setup-terraform == 'true'

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ inputs.terragrunt-version }}
      if: inputs.setup-terragrunt == 'true'

    - name: build and run digger
      if: ${{ !startsWith(github.action_ref, 'v') }}
      shell: bash
      run: |
          cd ${{ github.action_path }}
          go build -o digger ./cmd/digger
          chmod +x digger
          mv digger /usr/local/bin/digger
          cd ${{ github.workspace }}
          digger
    - name: run digger
      if: ${{ startsWith(github.action_ref, 'v') }}
      env:
        actionref: ${{ github.action_ref }}
      id: digger
      shell: bash
      run: |
        curl -sL https://github.com/diggerhq/digger/releases/download/${actionref}/digger-${{ runner.os  }}-${{ runner.arch }} -o digger
        chmod +x digger
        mv digger /usr/local/bin/digger
        cd ${{ github.workspace }}
        digger
    - name: generate artifact name based on issue number or pr number
      id: artifact
      shell: bash
      run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            echo "artifact=plans-${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "artifact=plans-${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi
    - name: upload plan
      uses: actions/upload-artifact@v3
      with:
          name: ${{ steps.artifact.outputs.artifact }}
          path: '*.tfplan'
          retention-days: 14

branding:
  icon: globe
  color: purple
