name: tfrun
description: Manage terraform collaboration
author: Digger

inputs:
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default

outputs:
  output:
    value: ${{ steps.tfrun.outputs.output }}
    description: The terraform output

runs:
  using: composite
  steps:
    - name: run tfrun
      id: tfrun
      shell: bash
      run: |
        curl -sL https://github.com/diggerhq/tfrun/releases/${{ github.action_ref }}/download/tfrun-${{ runner.os  }}-${{ runner.arch }} -o tfrun
        chmod +x tfrun
        ./tfrun ${{ inputs.workspace }}

branding:
  icon: globe
  color: purple
