name: tfrun
description: Manage terraform collaboration
author: Digger

inputs:
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default

outputs:
  output:
    description: The terraform output

runs:
  using: docker
  image: ./Dockerfile
  entrypoint: /entrypoint.sh

branding:
  icon: globe
  color: purple
