# Stage 1: Builder
FROM golang:1.22.4 AS builder

# Build arguments
ARG COMMIT_SHA
RUN echo "Commit SHA: ${COMMIT_SHA}"

# Set the working directory
WORKDIR $GOPATH/src/github.com/diggerhq/digger

# Cache Go dependencies by copying only the go.mod and go.sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the static binary
RUN go build -ldflags="-X 'main.Version=${COMMIT_SHA}'" -o next_exe ./next/

# Stage 2: Runner
FROM ubuntu:24.04-slim AS runner
ENV ATLAS_VERSION v0.16.0
ARG COMMIT_SHA
WORKDIR /app

# Install necessary packages and clean up in a single step
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates curl git && \
    rm -rf /var/lib/apt/lists/* && \
    update-ca-certificates

# Print commit SHA
RUN echo "Commit SHA: ${COMMIT_SHA}"

# Install Atlas
RUN curl -sSf https://atlasgo.sh | sh

#ENV GIN_MODE=release

# Expose the running port
EXPOSE 3000

# Copy binary and entrypoint
COPY --from=builder /go/src/github.com/diggerhq/digger/next_exe /app/next
COPY --from=builder /go/src/github.com/diggerhq/digger/next/scripts/entrypoint.sh /app/entrypoint.sh
ADD next/templates ./templates

# Set entrypoint and permissions
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]

