# fly.toml app configuration file generated for next-backend on 2024-07-19T08:47:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'next-backend'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[env]
  DIGGER_HOSTNAME = 'https://next-backend.digger.dev'
  
[build]
  dockerfile = 'Dockerfile_next'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
