// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiggerCiJob = "digger_ci_jobs"

// DiggerCiJob mapped from table <digger_ci_jobs>
type DiggerCiJob struct {
	ID                 string         `gorm:"column:id;primaryKey" json:"id"`
	Spectype           string         `gorm:"column:spectype" json:"spectype"`
	Commentid          string         `gorm:"column:commentid" json:"commentid"`
	Runname            string         `gorm:"column:runname" json:"runname"`
	Jobspec            []uint8        `gorm:"column:jobspec" json:"jobspec"`
	Reporterspec       []uint8        `gorm:"column:reporterspec" json:"reporterspec"`
	Commentupdaterspec []uint8        `gorm:"column:commentupdaterspec" json:"commentupdaterspec"`
	Lockspec           []uint8        `gorm:"column:lockspec" json:"lockspec"`
	Backendspec        []uint8        `gorm:"column:backendspec" json:"backendspec"`
	Vcsspec            []uint8        `gorm:"column:vcsspec" json:"vcsspec"`
	Policyspec         []uint8        `gorm:"column:policyspec" json:"policyspec"`
	Variablesspec      []uint8        `gorm:"column:variablesspec" json:"variablesspec"`
	CreatedAt          time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	WorkflowFile       string         `gorm:"column:workflow_file" json:"workflow_file"`
	WorkflowURL        string         `gorm:"column:workflow_url" json:"workflow_url"`
	Status             string         `gorm:"column:status" json:"status"`
	ResourcesCreated   int32          `gorm:"column:resources_created" json:"resources_created"`
	ResourcesUpdated   int32          `gorm:"column:resources_updated" json:"resources_updated"`
	ResourcesDeleted   int32          `gorm:"column:resources_deleted" json:"resources_deleted"`
	ProjectID          string         `gorm:"column:project_id" json:"project_id"`
}

// TableName DiggerCiJob's table name
func (*DiggerCiJob) TableName() string {
	return TableNameDiggerCiJob
}
