// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiggerCiJobToken = "digger_ci_job_tokens"

// DiggerCiJobToken mapped from table <digger_ci_job_tokens>
type DiggerCiJobToken struct {
	ID             string         `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Value          string         `gorm:"column:value" json:"value"`
	Expiry         time.Time      `gorm:"column:expiry" json:"expiry"`
	OrganisationID string         `gorm:"column:organisation_id" json:"organisation_id"`
	Type           string         `gorm:"column:type" json:"type"`
}

// TableName DiggerCiJobToken's table name
func (*DiggerCiJobToken) TableName() string {
	return TableNameDiggerCiJobToken
}
