// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGithubAppInstallationLink = "github_app_installation_links"

// GithubAppInstallationLink mapped from table <github_app_installation_links>
type GithubAppInstallationLink struct {
	ID                   string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt            time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	GithubInstallationID string         `gorm:"column:github_installation_id;not null" json:"github_installation_id"`
	OrganisationID       string         `gorm:"column:organisation_id;not null" json:"organisation_id"`
	Status               string         `gorm:"column:status" json:"status"`
}

// TableName GithubAppInstallationLink's table name
func (*GithubAppInstallationLink) TableName() string {
	return TableNameGithubAppInstallationLink
}
