// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSetting = "user_settings"

// UserSetting mapped from table <user_settings>
type UserSetting struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	ScheduleType         string    `gorm:"column:schedule_type" json:"schedule_type"`
	Schedule             string    `gorm:"column:schedule" json:"schedule"`
	SlackNotificationURL string    `gorm:"column:slack_notification_url" json:"slack_notification_url"`
	UserID               string    `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName UserSetting's table name
func (*UserSetting) TableName() string {
	return TableNameUserSetting
}
