/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthWorkosWebhooksRouteImport } from './routes/api/auth/workos/webhooks'
import { Route as AuthenticatedDashboardDashboardUnitsRouteImport } from './routes/_authenticated/_dashboard/dashboard/units'
import { Route as AuthenticatedDashboardDashboardSettingsRouteImport } from './routes/_authenticated/_dashboard/dashboard/settings'
import { Route as AuthenticatedDashboardDashboardReposRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos'
import { Route as AuthenticatedDashboardDashboardProjectsRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects'
import { Route as AuthenticatedDashboardDashboardOnboardingRouteImport } from './routes/_authenticated/_dashboard/dashboard/onboarding'
import { Route as AuthenticatedDashboardDashboardDriftRouteImport } from './routes/_authenticated/_dashboard/dashboard/drift'
import { Route as AuthenticatedDashboardDashboardConnectionsRouteImport } from './routes/_authenticated/_dashboard/dashboard/connections'
import { Route as AuthenticatedDashboardDashboardUnitsIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/units.index'
import { Route as AuthenticatedDashboardDashboardReposIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.index'
import { Route as AuthenticatedDashboardDashboardProjectsIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects.index'
import { Route as AuthenticatedDashboardDashboardUnitsUnitIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/units.$unitId'
import { Route as AuthenticatedDashboardDashboardReposConnectRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.connect'
import { Route as AuthenticatedDashboardDashboardReposRepoIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.$repoId'
import { Route as AuthenticatedDashboardDashboardProjectsProjectIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects.$projectId'
import { Route as AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/connections.$connectionId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWorkosWebhooksRoute = ApiAuthWorkosWebhooksRouteImport.update({
  id: '/api/auth/workos/webhooks',
  path: '/api/auth/workos/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardDashboardUnitsRoute =
  AuthenticatedDashboardDashboardUnitsRouteImport.update({
    id: '/dashboard/units',
    path: '/dashboard/units',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardSettingsRoute =
  AuthenticatedDashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardReposRoute =
  AuthenticatedDashboardDashboardReposRouteImport.update({
    id: '/dashboard/repos',
    path: '/dashboard/repos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsRoute =
  AuthenticatedDashboardDashboardProjectsRouteImport.update({
    id: '/dashboard/projects',
    path: '/dashboard/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardOnboardingRoute =
  AuthenticatedDashboardDashboardOnboardingRouteImport.update({
    id: '/dashboard/onboarding',
    path: '/dashboard/onboarding',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardDriftRoute =
  AuthenticatedDashboardDashboardDriftRouteImport.update({
    id: '/dashboard/drift',
    path: '/dashboard/drift',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardConnectionsRoute =
  AuthenticatedDashboardDashboardConnectionsRouteImport.update({
    id: '/dashboard/connections',
    path: '/dashboard/connections',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardUnitsIndexRoute =
  AuthenticatedDashboardDashboardUnitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardUnitsRoute,
  } as any)
const AuthenticatedDashboardDashboardReposIndexRoute =
  AuthenticatedDashboardDashboardReposIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsIndexRoute =
  AuthenticatedDashboardDashboardProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardDashboardUnitsUnitIdRoute =
  AuthenticatedDashboardDashboardUnitsUnitIdRouteImport.update({
    id: '/$unitId',
    path: '/$unitId',
    getParentRoute: () => AuthenticatedDashboardDashboardUnitsRoute,
  } as any)
const AuthenticatedDashboardDashboardReposConnectRoute =
  AuthenticatedDashboardDashboardReposConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardReposRepoIdRoute =
  AuthenticatedDashboardDashboardReposRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsProjectIdRoute =
  AuthenticatedDashboardDashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedDashboardDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardDashboardConnectionsConnectionIdRoute =
  AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedDashboardDashboardConnectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  '/dashboard/repos': typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRoute
  '/dashboard/units': typeof AuthenticatedDashboardDashboardUnitsRouteWithChildren
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardDashboardProjectsProjectIdRoute
  '/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/dashboard/projects/': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/dashboard/repos/': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/dashboard/units/': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRoute
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardDashboardProjectsProjectIdRoute
  '/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/dashboard/repos': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/dashboard/units': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/_dashboard/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/_authenticated/_dashboard/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/_authenticated/_dashboard/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/_authenticated/_dashboard/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  '/_authenticated/_dashboard/dashboard/repos': typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  '/_authenticated/_dashboard/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRoute
  '/_authenticated/_dashboard/dashboard/units': typeof AuthenticatedDashboardDashboardUnitsRouteWithChildren
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/_authenticated/_dashboard/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/_authenticated/_dashboard/dashboard/projects/$projectId': typeof AuthenticatedDashboardDashboardProjectsProjectIdRoute
  '/_authenticated/_dashboard/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/_authenticated/_dashboard/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/_authenticated/_dashboard/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/_authenticated/_dashboard/dashboard/projects/': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/_authenticated/_dashboard/dashboard/repos/': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/_authenticated/_dashboard/dashboard/units/': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/api/auth/callback'
    | '/dashboard/connections'
    | '/dashboard/drift'
    | '/dashboard/onboarding'
    | '/dashboard/projects'
    | '/dashboard/repos'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/api/auth/workos/webhooks'
    | '/dashboard/connections/$connectionId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/repos/$repoId'
    | '/dashboard/repos/connect'
    | '/dashboard/units/$unitId'
    | '/dashboard/projects/'
    | '/dashboard/repos/'
    | '/dashboard/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/api/auth/callback'
    | '/dashboard/connections'
    | '/dashboard/drift'
    | '/dashboard/onboarding'
    | '/dashboard/settings'
    | '/api/auth/workos/webhooks'
    | '/dashboard/connections/$connectionId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/repos/$repoId'
    | '/dashboard/repos/connect'
    | '/dashboard/units/$unitId'
    | '/dashboard/projects'
    | '/dashboard/repos'
    | '/dashboard/units'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/_dashboard'
    | '/api/auth/callback'
    | '/_authenticated/_dashboard/dashboard/connections'
    | '/_authenticated/_dashboard/dashboard/drift'
    | '/_authenticated/_dashboard/dashboard/onboarding'
    | '/_authenticated/_dashboard/dashboard/projects'
    | '/_authenticated/_dashboard/dashboard/repos'
    | '/_authenticated/_dashboard/dashboard/settings'
    | '/_authenticated/_dashboard/dashboard/units'
    | '/api/auth/workos/webhooks'
    | '/_authenticated/_dashboard/dashboard/connections/$connectionId'
    | '/_authenticated/_dashboard/dashboard/projects/$projectId'
    | '/_authenticated/_dashboard/dashboard/repos/$repoId'
    | '/_authenticated/_dashboard/dashboard/repos/connect'
    | '/_authenticated/_dashboard/dashboard/units/$unitId'
    | '/_authenticated/_dashboard/dashboard/projects/'
    | '/_authenticated/_dashboard/dashboard/repos/'
    | '/_authenticated/_dashboard/dashboard/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthWorkosWebhooksRoute: typeof ApiAuthWorkosWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/workos/webhooks': {
      id: '/api/auth/workos/webhooks'
      path: '/api/auth/workos/webhooks'
      fullPath: '/api/auth/workos/webhooks'
      preLoaderRoute: typeof ApiAuthWorkosWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/dashboard/units': {
      id: '/_authenticated/_dashboard/dashboard/units'
      path: '/dashboard/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardUnitsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/settings': {
      id: '/_authenticated/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/repos': {
      id: '/_authenticated/_dashboard/dashboard/repos'
      path: '/dashboard/repos'
      fullPath: '/dashboard/repos'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/projects': {
      id: '/_authenticated/_dashboard/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/onboarding': {
      id: '/_authenticated/_dashboard/dashboard/onboarding'
      path: '/dashboard/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardOnboardingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/drift': {
      id: '/_authenticated/_dashboard/dashboard/drift'
      path: '/dashboard/drift'
      fullPath: '/dashboard/drift'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardDriftRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/connections': {
      id: '/_authenticated/_dashboard/dashboard/connections'
      path: '/dashboard/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardConnectionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/units/': {
      id: '/_authenticated/_dashboard/dashboard/units/'
      path: '/'
      fullPath: '/dashboard/units/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardUnitsRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/': {
      id: '/_authenticated/_dashboard/dashboard/repos/'
      path: '/'
      fullPath: '/dashboard/repos/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/projects/': {
      id: '/_authenticated/_dashboard/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardProjectsRoute
    }
    '/_authenticated/_dashboard/dashboard/units/$unitId': {
      id: '/_authenticated/_dashboard/dashboard/units/$unitId'
      path: '/$unitId'
      fullPath: '/dashboard/units/$unitId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardUnitsRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/connect': {
      id: '/_authenticated/_dashboard/dashboard/repos/connect'
      path: '/connect'
      fullPath: '/dashboard/repos/connect'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposConnectRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/$repoId': {
      id: '/_authenticated/_dashboard/dashboard/repos/$repoId'
      path: '/$repoId'
      fullPath: '/dashboard/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/projects/$projectId': {
      id: '/_authenticated/_dashboard/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardProjectsRoute
    }
    '/_authenticated/_dashboard/dashboard/connections/$connectionId': {
      id: '/_authenticated/_dashboard/dashboard/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/dashboard/connections/$connectionId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardConnectionsRoute
    }
  }
}

interface AuthenticatedDashboardDashboardConnectionsRouteChildren {
  AuthenticatedDashboardDashboardConnectionsConnectionIdRoute: typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
}

const AuthenticatedDashboardDashboardConnectionsRouteChildren: AuthenticatedDashboardDashboardConnectionsRouteChildren =
  {
    AuthenticatedDashboardDashboardConnectionsConnectionIdRoute:
      AuthenticatedDashboardDashboardConnectionsConnectionIdRoute,
  }

const AuthenticatedDashboardDashboardConnectionsRouteWithChildren =
  AuthenticatedDashboardDashboardConnectionsRoute._addFileChildren(
    AuthenticatedDashboardDashboardConnectionsRouteChildren,
  )

interface AuthenticatedDashboardDashboardProjectsRouteChildren {
  AuthenticatedDashboardDashboardProjectsProjectIdRoute: typeof AuthenticatedDashboardDashboardProjectsProjectIdRoute
  AuthenticatedDashboardDashboardProjectsIndexRoute: typeof AuthenticatedDashboardDashboardProjectsIndexRoute
}

const AuthenticatedDashboardDashboardProjectsRouteChildren: AuthenticatedDashboardDashboardProjectsRouteChildren =
  {
    AuthenticatedDashboardDashboardProjectsProjectIdRoute:
      AuthenticatedDashboardDashboardProjectsProjectIdRoute,
    AuthenticatedDashboardDashboardProjectsIndexRoute:
      AuthenticatedDashboardDashboardProjectsIndexRoute,
  }

const AuthenticatedDashboardDashboardProjectsRouteWithChildren =
  AuthenticatedDashboardDashboardProjectsRoute._addFileChildren(
    AuthenticatedDashboardDashboardProjectsRouteChildren,
  )

interface AuthenticatedDashboardDashboardReposRouteChildren {
  AuthenticatedDashboardDashboardReposRepoIdRoute: typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  AuthenticatedDashboardDashboardReposConnectRoute: typeof AuthenticatedDashboardDashboardReposConnectRoute
  AuthenticatedDashboardDashboardReposIndexRoute: typeof AuthenticatedDashboardDashboardReposIndexRoute
}

const AuthenticatedDashboardDashboardReposRouteChildren: AuthenticatedDashboardDashboardReposRouteChildren =
  {
    AuthenticatedDashboardDashboardReposRepoIdRoute:
      AuthenticatedDashboardDashboardReposRepoIdRoute,
    AuthenticatedDashboardDashboardReposConnectRoute:
      AuthenticatedDashboardDashboardReposConnectRoute,
    AuthenticatedDashboardDashboardReposIndexRoute:
      AuthenticatedDashboardDashboardReposIndexRoute,
  }

const AuthenticatedDashboardDashboardReposRouteWithChildren =
  AuthenticatedDashboardDashboardReposRoute._addFileChildren(
    AuthenticatedDashboardDashboardReposRouteChildren,
  )

interface AuthenticatedDashboardDashboardUnitsRouteChildren {
  AuthenticatedDashboardDashboardUnitsUnitIdRoute: typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  AuthenticatedDashboardDashboardUnitsIndexRoute: typeof AuthenticatedDashboardDashboardUnitsIndexRoute
}

const AuthenticatedDashboardDashboardUnitsRouteChildren: AuthenticatedDashboardDashboardUnitsRouteChildren =
  {
    AuthenticatedDashboardDashboardUnitsUnitIdRoute:
      AuthenticatedDashboardDashboardUnitsUnitIdRoute,
    AuthenticatedDashboardDashboardUnitsIndexRoute:
      AuthenticatedDashboardDashboardUnitsIndexRoute,
  }

const AuthenticatedDashboardDashboardUnitsRouteWithChildren =
  AuthenticatedDashboardDashboardUnitsRoute._addFileChildren(
    AuthenticatedDashboardDashboardUnitsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDashboardConnectionsRoute: typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  AuthenticatedDashboardDashboardDriftRoute: typeof AuthenticatedDashboardDashboardDriftRoute
  AuthenticatedDashboardDashboardOnboardingRoute: typeof AuthenticatedDashboardDashboardOnboardingRoute
  AuthenticatedDashboardDashboardProjectsRoute: typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  AuthenticatedDashboardDashboardReposRoute: typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  AuthenticatedDashboardDashboardSettingsRoute: typeof AuthenticatedDashboardDashboardSettingsRoute
  AuthenticatedDashboardDashboardUnitsRoute: typeof AuthenticatedDashboardDashboardUnitsRouteWithChildren
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardConnectionsRoute:
      AuthenticatedDashboardDashboardConnectionsRouteWithChildren,
    AuthenticatedDashboardDashboardDriftRoute:
      AuthenticatedDashboardDashboardDriftRoute,
    AuthenticatedDashboardDashboardOnboardingRoute:
      AuthenticatedDashboardDashboardOnboardingRoute,
    AuthenticatedDashboardDashboardProjectsRoute:
      AuthenticatedDashboardDashboardProjectsRouteWithChildren,
    AuthenticatedDashboardDashboardReposRoute:
      AuthenticatedDashboardDashboardReposRouteWithChildren,
    AuthenticatedDashboardDashboardSettingsRoute:
      AuthenticatedDashboardDashboardSettingsRoute,
    AuthenticatedDashboardDashboardUnitsRoute:
      AuthenticatedDashboardDashboardUnitsRouteWithChildren,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthWorkosWebhooksRoute: ApiAuthWorkosWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
