/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TfeSplatRouteImport } from './routes/tfe/$'
import { Route as OrchestratorJob_artefactsRouteImport } from './routes/_orchestrator/job_artefacts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as OrchestratorGithubWebhookRouteImport } from './routes/orchestrator/github/webhook'
import { Route as OrchestratorGithubCallbackRouteImport } from './routes/orchestrator/github/callback'
import { Route as AppSettingsTokensRouteImport } from './routes/app/settings.tokens'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthWorkosWebhooksRouteImport } from './routes/api/auth/workos/webhooks'
import { Route as ApiAuthWorkosSwitchOrgRouteImport } from './routes/api/auth/workos/switch-org'
import { Route as OrchestratorReposNamespaceReportProjectsRouteImport } from './routes/_orchestrator/repos/$namespace/report-projects'
import { Route as OrchestratorOrgsOrgIdPlan_policyRouteImport } from './routes/_orchestrator/orgs/$orgId.plan_policy'
import { Route as OrchestratorOrgsOrgIdAccess_policyRouteImport } from './routes/_orchestrator/orgs/$orgId.access_policy'
import { Route as AuthenticatedDashboardDashboardSettingsRouteImport } from './routes/_authenticated/_dashboard/dashboard/settings'
import { Route as AuthenticatedDashboardDashboardReposRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos'
import { Route as AuthenticatedDashboardDashboardProjectsRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects'
import { Route as AuthenticatedDashboardDashboardOnboardingRouteImport } from './routes/_authenticated/_dashboard/dashboard/onboarding'
import { Route as AuthenticatedDashboardDashboardDriftRouteImport } from './routes/_authenticated/_dashboard/dashboard/drift'
import { Route as AuthenticatedDashboardDashboardConnectionsRouteImport } from './routes/_authenticated/_dashboard/dashboard/connections'
import { Route as AuthenticatedDashboardDashboardUnitsIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/units.index'
import { Route as AuthenticatedDashboardDashboardReposIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.index'
import { Route as AuthenticatedDashboardDashboardProjectsIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects.index'
import { Route as AuthenticatedDashboardDashboardUnitsUnitIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/units.$unitId'
import { Route as AuthenticatedDashboardDashboardSettingsUserRouteImport } from './routes/_authenticated/_dashboard/dashboard/settings.user'
import { Route as AuthenticatedDashboardDashboardSettingsTokensRouteImport } from './routes/_authenticated/_dashboard/dashboard/settings.tokens'
import { Route as AuthenticatedDashboardDashboardReposConnectRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.connect'
import { Route as AuthenticatedDashboardDashboardReposRepoIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/repos.$repoId'
import { Route as AuthenticatedDashboardDashboardProjectsProjectidRouteImport } from './routes/_authenticated/_dashboard/dashboard/projects.$projectid'
import { Route as AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport } from './routes/_authenticated/_dashboard/dashboard/connections.$connectionId'
import { Route as OrchestratorReposNamespaceProjectsProjectNamePlan_policyRouteImport } from './routes/_orchestrator/repos/$namespace/projects/$projectName/plan_policy'
import { Route as OrchestratorReposNamespaceProjectsProjectNameAccess_policyRouteImport } from './routes/_orchestrator/repos/$namespace/projects/$projectName/access_policy'
import { Route as OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRouteImport } from './routes/_orchestrator/repos/$namespace/projects/$projectName/jobs.$jobId.set-status'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TfeSplatRoute = TfeSplatRouteImport.update({
  id: '/tfe/$',
  path: '/tfe/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorJob_artefactsRoute =
  OrchestratorJob_artefactsRouteImport.update({
    id: '/_orchestrator/job_artefacts',
    path: '/job_artefacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OrchestratorGithubWebhookRoute =
  OrchestratorGithubWebhookRouteImport.update({
    id: '/orchestrator/github/webhook',
    path: '/orchestrator/github/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrchestratorGithubCallbackRoute =
  OrchestratorGithubCallbackRouteImport.update({
    id: '/orchestrator/github/callback',
    path: '/orchestrator/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: '/app/settings/tokens',
  path: '/app/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWorkosWebhooksRoute = ApiAuthWorkosWebhooksRouteImport.update({
  id: '/api/auth/workos/webhooks',
  path: '/api/auth/workos/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWorkosSwitchOrgRoute = ApiAuthWorkosSwitchOrgRouteImport.update({
  id: '/api/auth/workos/switch-org',
  path: '/api/auth/workos/switch-org',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorReposNamespaceReportProjectsRoute =
  OrchestratorReposNamespaceReportProjectsRouteImport.update({
    id: '/_orchestrator/repos/$namespace/report-projects',
    path: '/repos/$namespace/report-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrchestratorOrgsOrgIdPlan_policyRoute =
  OrchestratorOrgsOrgIdPlan_policyRouteImport.update({
    id: '/_orchestrator/orgs/$orgId/plan_policy',
    path: '/orgs/$orgId/plan_policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrchestratorOrgsOrgIdAccess_policyRoute =
  OrchestratorOrgsOrgIdAccess_policyRouteImport.update({
    id: '/_orchestrator/orgs/$orgId/access_policy',
    path: '/orgs/$orgId/access_policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardDashboardSettingsRoute =
  AuthenticatedDashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardReposRoute =
  AuthenticatedDashboardDashboardReposRouteImport.update({
    id: '/dashboard/repos',
    path: '/dashboard/repos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsRoute =
  AuthenticatedDashboardDashboardProjectsRouteImport.update({
    id: '/dashboard/projects',
    path: '/dashboard/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardOnboardingRoute =
  AuthenticatedDashboardDashboardOnboardingRouteImport.update({
    id: '/dashboard/onboarding',
    path: '/dashboard/onboarding',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardDriftRoute =
  AuthenticatedDashboardDashboardDriftRouteImport.update({
    id: '/dashboard/drift',
    path: '/dashboard/drift',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardConnectionsRoute =
  AuthenticatedDashboardDashboardConnectionsRouteImport.update({
    id: '/dashboard/connections',
    path: '/dashboard/connections',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardUnitsIndexRoute =
  AuthenticatedDashboardDashboardUnitsIndexRouteImport.update({
    id: '/dashboard/units/',
    path: '/dashboard/units/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardReposIndexRoute =
  AuthenticatedDashboardDashboardReposIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsIndexRoute =
  AuthenticatedDashboardDashboardProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardDashboardUnitsUnitIdRoute =
  AuthenticatedDashboardDashboardUnitsUnitIdRouteImport.update({
    id: '/dashboard/units/$unitId',
    path: '/dashboard/units/$unitId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardSettingsUserRoute =
  AuthenticatedDashboardDashboardSettingsUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => AuthenticatedDashboardDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardDashboardSettingsTokensRoute =
  AuthenticatedDashboardDashboardSettingsTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedDashboardDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardDashboardReposConnectRoute =
  AuthenticatedDashboardDashboardReposConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardReposRepoIdRoute =
  AuthenticatedDashboardDashboardReposRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => AuthenticatedDashboardDashboardReposRoute,
  } as any)
const AuthenticatedDashboardDashboardProjectsProjectidRoute =
  AuthenticatedDashboardDashboardProjectsProjectidRouteImport.update({
    id: '/$projectid',
    path: '/$projectid',
    getParentRoute: () => AuthenticatedDashboardDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardDashboardConnectionsConnectionIdRoute =
  AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedDashboardDashboardConnectionsRoute,
  } as any)
const OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute =
  OrchestratorReposNamespaceProjectsProjectNamePlan_policyRouteImport.update({
    id: '/_orchestrator/repos/$namespace/projects/$projectName/plan_policy',
    path: '/repos/$namespace/projects/$projectName/plan_policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute =
  OrchestratorReposNamespaceProjectsProjectNameAccess_policyRouteImport.update({
    id: '/_orchestrator/repos/$namespace/projects/$projectName/access_policy',
    path: '/repos/$namespace/projects/$projectName/access_policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute =
  OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRouteImport.update(
    {
      id: '/_orchestrator/repos/$namespace/projects/$projectName/jobs/$jobId/set-status',
      path: '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/job_artefacts': typeof OrchestratorJob_artefactsRoute
  '/tfe/$': typeof TfeSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app/settings/tokens': typeof AppSettingsTokensRoute
  '/orchestrator/github/callback': typeof OrchestratorGithubCallbackRoute
  '/orchestrator/github/webhook': typeof OrchestratorGithubWebhookRoute
  '/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  '/dashboard/repos': typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRouteWithChildren
  '/orgs/$orgId/access_policy': typeof OrchestratorOrgsOrgIdAccess_policyRoute
  '/orgs/$orgId/plan_policy': typeof OrchestratorOrgsOrgIdPlan_policyRoute
  '/repos/$namespace/report-projects': typeof OrchestratorReposNamespaceReportProjectsRoute
  '/api/auth/workos/switch-org': typeof ApiAuthWorkosSwitchOrgRoute
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/dashboard/projects/$projectid': typeof AuthenticatedDashboardDashboardProjectsProjectidRoute
  '/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/dashboard/settings/tokens': typeof AuthenticatedDashboardDashboardSettingsTokensRoute
  '/dashboard/settings/user': typeof AuthenticatedDashboardDashboardSettingsUserRoute
  '/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/dashboard/projects/': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/dashboard/repos/': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/dashboard/units': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
  '/repos/$namespace/projects/$projectName/access_policy': typeof OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute
  '/repos/$namespace/projects/$projectName/plan_policy': typeof OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute
  '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status': typeof OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/job_artefacts': typeof OrchestratorJob_artefactsRoute
  '/tfe/$': typeof TfeSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app/settings/tokens': typeof AppSettingsTokensRoute
  '/orchestrator/github/callback': typeof OrchestratorGithubCallbackRoute
  '/orchestrator/github/webhook': typeof OrchestratorGithubWebhookRoute
  '/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRouteWithChildren
  '/orgs/$orgId/access_policy': typeof OrchestratorOrgsOrgIdAccess_policyRoute
  '/orgs/$orgId/plan_policy': typeof OrchestratorOrgsOrgIdPlan_policyRoute
  '/repos/$namespace/report-projects': typeof OrchestratorReposNamespaceReportProjectsRoute
  '/api/auth/workos/switch-org': typeof ApiAuthWorkosSwitchOrgRoute
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/dashboard/projects/$projectid': typeof AuthenticatedDashboardDashboardProjectsProjectidRoute
  '/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/dashboard/settings/tokens': typeof AuthenticatedDashboardDashboardSettingsTokensRoute
  '/dashboard/settings/user': typeof AuthenticatedDashboardDashboardSettingsUserRoute
  '/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/dashboard/repos': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/dashboard/units': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
  '/repos/$namespace/projects/$projectName/access_policy': typeof OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute
  '/repos/$namespace/projects/$projectName/plan_policy': typeof OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute
  '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status': typeof OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_orchestrator/job_artefacts': typeof OrchestratorJob_artefactsRoute
  '/tfe/$': typeof TfeSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/app/settings/tokens': typeof AppSettingsTokensRoute
  '/orchestrator/github/callback': typeof OrchestratorGithubCallbackRoute
  '/orchestrator/github/webhook': typeof OrchestratorGithubWebhookRoute
  '/_authenticated/_dashboard/dashboard/connections': typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  '/_authenticated/_dashboard/dashboard/drift': typeof AuthenticatedDashboardDashboardDriftRoute
  '/_authenticated/_dashboard/dashboard/onboarding': typeof AuthenticatedDashboardDashboardOnboardingRoute
  '/_authenticated/_dashboard/dashboard/projects': typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  '/_authenticated/_dashboard/dashboard/repos': typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  '/_authenticated/_dashboard/dashboard/settings': typeof AuthenticatedDashboardDashboardSettingsRouteWithChildren
  '/_orchestrator/orgs/$orgId/access_policy': typeof OrchestratorOrgsOrgIdAccess_policyRoute
  '/_orchestrator/orgs/$orgId/plan_policy': typeof OrchestratorOrgsOrgIdPlan_policyRoute
  '/_orchestrator/repos/$namespace/report-projects': typeof OrchestratorReposNamespaceReportProjectsRoute
  '/api/auth/workos/switch-org': typeof ApiAuthWorkosSwitchOrgRoute
  '/api/auth/workos/webhooks': typeof ApiAuthWorkosWebhooksRoute
  '/_authenticated/_dashboard/dashboard/connections/$connectionId': typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
  '/_authenticated/_dashboard/dashboard/projects/$projectid': typeof AuthenticatedDashboardDashboardProjectsProjectidRoute
  '/_authenticated/_dashboard/dashboard/repos/$repoId': typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  '/_authenticated/_dashboard/dashboard/repos/connect': typeof AuthenticatedDashboardDashboardReposConnectRoute
  '/_authenticated/_dashboard/dashboard/settings/tokens': typeof AuthenticatedDashboardDashboardSettingsTokensRoute
  '/_authenticated/_dashboard/dashboard/settings/user': typeof AuthenticatedDashboardDashboardSettingsUserRoute
  '/_authenticated/_dashboard/dashboard/units/$unitId': typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  '/_authenticated/_dashboard/dashboard/projects/': typeof AuthenticatedDashboardDashboardProjectsIndexRoute
  '/_authenticated/_dashboard/dashboard/repos/': typeof AuthenticatedDashboardDashboardReposIndexRoute
  '/_authenticated/_dashboard/dashboard/units/': typeof AuthenticatedDashboardDashboardUnitsIndexRoute
  '/_orchestrator/repos/$namespace/projects/$projectName/access_policy': typeof OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute
  '/_orchestrator/repos/$namespace/projects/$projectName/plan_policy': typeof OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute
  '/_orchestrator/repos/$namespace/projects/$projectName/jobs/$jobId/set-status': typeof OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/job_artefacts'
    | '/tfe/$'
    | '/api/auth/callback'
    | '/app/settings/tokens'
    | '/orchestrator/github/callback'
    | '/orchestrator/github/webhook'
    | '/dashboard/connections'
    | '/dashboard/drift'
    | '/dashboard/onboarding'
    | '/dashboard/projects'
    | '/dashboard/repos'
    | '/dashboard/settings'
    | '/orgs/$orgId/access_policy'
    | '/orgs/$orgId/plan_policy'
    | '/repos/$namespace/report-projects'
    | '/api/auth/workos/switch-org'
    | '/api/auth/workos/webhooks'
    | '/dashboard/connections/$connectionId'
    | '/dashboard/projects/$projectid'
    | '/dashboard/repos/$repoId'
    | '/dashboard/repos/connect'
    | '/dashboard/settings/tokens'
    | '/dashboard/settings/user'
    | '/dashboard/units/$unitId'
    | '/dashboard/projects/'
    | '/dashboard/repos/'
    | '/dashboard/units'
    | '/repos/$namespace/projects/$projectName/access_policy'
    | '/repos/$namespace/projects/$projectName/plan_policy'
    | '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/job_artefacts'
    | '/tfe/$'
    | '/api/auth/callback'
    | '/app/settings/tokens'
    | '/orchestrator/github/callback'
    | '/orchestrator/github/webhook'
    | '/dashboard/connections'
    | '/dashboard/drift'
    | '/dashboard/onboarding'
    | '/dashboard/settings'
    | '/orgs/$orgId/access_policy'
    | '/orgs/$orgId/plan_policy'
    | '/repos/$namespace/report-projects'
    | '/api/auth/workos/switch-org'
    | '/api/auth/workos/webhooks'
    | '/dashboard/connections/$connectionId'
    | '/dashboard/projects/$projectid'
    | '/dashboard/repos/$repoId'
    | '/dashboard/repos/connect'
    | '/dashboard/settings/tokens'
    | '/dashboard/settings/user'
    | '/dashboard/units/$unitId'
    | '/dashboard/projects'
    | '/dashboard/repos'
    | '/dashboard/units'
    | '/repos/$namespace/projects/$projectName/access_policy'
    | '/repos/$namespace/projects/$projectName/plan_policy'
    | '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/_dashboard'
    | '/_orchestrator/job_artefacts'
    | '/tfe/$'
    | '/api/auth/callback'
    | '/app/settings/tokens'
    | '/orchestrator/github/callback'
    | '/orchestrator/github/webhook'
    | '/_authenticated/_dashboard/dashboard/connections'
    | '/_authenticated/_dashboard/dashboard/drift'
    | '/_authenticated/_dashboard/dashboard/onboarding'
    | '/_authenticated/_dashboard/dashboard/projects'
    | '/_authenticated/_dashboard/dashboard/repos'
    | '/_authenticated/_dashboard/dashboard/settings'
    | '/_orchestrator/orgs/$orgId/access_policy'
    | '/_orchestrator/orgs/$orgId/plan_policy'
    | '/_orchestrator/repos/$namespace/report-projects'
    | '/api/auth/workos/switch-org'
    | '/api/auth/workos/webhooks'
    | '/_authenticated/_dashboard/dashboard/connections/$connectionId'
    | '/_authenticated/_dashboard/dashboard/projects/$projectid'
    | '/_authenticated/_dashboard/dashboard/repos/$repoId'
    | '/_authenticated/_dashboard/dashboard/repos/connect'
    | '/_authenticated/_dashboard/dashboard/settings/tokens'
    | '/_authenticated/_dashboard/dashboard/settings/user'
    | '/_authenticated/_dashboard/dashboard/units/$unitId'
    | '/_authenticated/_dashboard/dashboard/projects/'
    | '/_authenticated/_dashboard/dashboard/repos/'
    | '/_authenticated/_dashboard/dashboard/units/'
    | '/_orchestrator/repos/$namespace/projects/$projectName/access_policy'
    | '/_orchestrator/repos/$namespace/projects/$projectName/plan_policy'
    | '/_orchestrator/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  OrchestratorJob_artefactsRoute: typeof OrchestratorJob_artefactsRoute
  TfeSplatRoute: typeof TfeSplatRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute
  OrchestratorGithubCallbackRoute: typeof OrchestratorGithubCallbackRoute
  OrchestratorGithubWebhookRoute: typeof OrchestratorGithubWebhookRoute
  OrchestratorOrgsOrgIdAccess_policyRoute: typeof OrchestratorOrgsOrgIdAccess_policyRoute
  OrchestratorOrgsOrgIdPlan_policyRoute: typeof OrchestratorOrgsOrgIdPlan_policyRoute
  OrchestratorReposNamespaceReportProjectsRoute: typeof OrchestratorReposNamespaceReportProjectsRoute
  ApiAuthWorkosSwitchOrgRoute: typeof ApiAuthWorkosSwitchOrgRoute
  ApiAuthWorkosWebhooksRoute: typeof ApiAuthWorkosWebhooksRoute
  OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute: typeof OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute
  OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute: typeof OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute
  OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute: typeof OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tfe/$': {
      id: '/tfe/$'
      path: '/tfe/$'
      fullPath: '/tfe/$'
      preLoaderRoute: typeof TfeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/job_artefacts': {
      id: '/_orchestrator/job_artefacts'
      path: '/job_artefacts'
      fullPath: '/job_artefacts'
      preLoaderRoute: typeof OrchestratorJob_artefactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/orchestrator/github/webhook': {
      id: '/orchestrator/github/webhook'
      path: '/orchestrator/github/webhook'
      fullPath: '/orchestrator/github/webhook'
      preLoaderRoute: typeof OrchestratorGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator/github/callback': {
      id: '/orchestrator/github/callback'
      path: '/orchestrator/github/callback'
      fullPath: '/orchestrator/github/callback'
      preLoaderRoute: typeof OrchestratorGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/tokens': {
      id: '/app/settings/tokens'
      path: '/app/settings/tokens'
      fullPath: '/app/settings/tokens'
      preLoaderRoute: typeof AppSettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/workos/webhooks': {
      id: '/api/auth/workos/webhooks'
      path: '/api/auth/workos/webhooks'
      fullPath: '/api/auth/workos/webhooks'
      preLoaderRoute: typeof ApiAuthWorkosWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/workos/switch-org': {
      id: '/api/auth/workos/switch-org'
      path: '/api/auth/workos/switch-org'
      fullPath: '/api/auth/workos/switch-org'
      preLoaderRoute: typeof ApiAuthWorkosSwitchOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/repos/$namespace/report-projects': {
      id: '/_orchestrator/repos/$namespace/report-projects'
      path: '/repos/$namespace/report-projects'
      fullPath: '/repos/$namespace/report-projects'
      preLoaderRoute: typeof OrchestratorReposNamespaceReportProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/orgs/$orgId/plan_policy': {
      id: '/_orchestrator/orgs/$orgId/plan_policy'
      path: '/orgs/$orgId/plan_policy'
      fullPath: '/orgs/$orgId/plan_policy'
      preLoaderRoute: typeof OrchestratorOrgsOrgIdPlan_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/orgs/$orgId/access_policy': {
      id: '/_orchestrator/orgs/$orgId/access_policy'
      path: '/orgs/$orgId/access_policy'
      fullPath: '/orgs/$orgId/access_policy'
      preLoaderRoute: typeof OrchestratorOrgsOrgIdAccess_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/dashboard/settings': {
      id: '/_authenticated/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/repos': {
      id: '/_authenticated/_dashboard/dashboard/repos'
      path: '/dashboard/repos'
      fullPath: '/dashboard/repos'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/projects': {
      id: '/_authenticated/_dashboard/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/onboarding': {
      id: '/_authenticated/_dashboard/dashboard/onboarding'
      path: '/dashboard/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardOnboardingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/drift': {
      id: '/_authenticated/_dashboard/dashboard/drift'
      path: '/dashboard/drift'
      fullPath: '/dashboard/drift'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardDriftRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/connections': {
      id: '/_authenticated/_dashboard/dashboard/connections'
      path: '/dashboard/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardConnectionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/units/': {
      id: '/_authenticated/_dashboard/dashboard/units/'
      path: '/dashboard/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/': {
      id: '/_authenticated/_dashboard/dashboard/repos/'
      path: '/'
      fullPath: '/dashboard/repos/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/projects/': {
      id: '/_authenticated/_dashboard/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardProjectsRoute
    }
    '/_authenticated/_dashboard/dashboard/units/$unitId': {
      id: '/_authenticated/_dashboard/dashboard/units/$unitId'
      path: '/dashboard/units/$unitId'
      fullPath: '/dashboard/units/$unitId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard/settings/user': {
      id: '/_authenticated/_dashboard/dashboard/settings/user'
      path: '/user'
      fullPath: '/dashboard/settings/user'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardSettingsUserRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/dashboard/settings/tokens': {
      id: '/_authenticated/_dashboard/dashboard/settings/tokens'
      path: '/tokens'
      fullPath: '/dashboard/settings/tokens'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardSettingsTokensRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/connect': {
      id: '/_authenticated/_dashboard/dashboard/repos/connect'
      path: '/connect'
      fullPath: '/dashboard/repos/connect'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposConnectRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/repos/$repoId': {
      id: '/_authenticated/_dashboard/dashboard/repos/$repoId'
      path: '/$repoId'
      fullPath: '/dashboard/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardReposRoute
    }
    '/_authenticated/_dashboard/dashboard/projects/$projectid': {
      id: '/_authenticated/_dashboard/dashboard/projects/$projectid'
      path: '/$projectid'
      fullPath: '/dashboard/projects/$projectid'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardProjectsProjectidRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardProjectsRoute
    }
    '/_authenticated/_dashboard/dashboard/connections/$connectionId': {
      id: '/_authenticated/_dashboard/dashboard/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/dashboard/connections/$connectionId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardConnectionsRoute
    }
    '/_orchestrator/repos/$namespace/projects/$projectName/plan_policy': {
      id: '/_orchestrator/repos/$namespace/projects/$projectName/plan_policy'
      path: '/repos/$namespace/projects/$projectName/plan_policy'
      fullPath: '/repos/$namespace/projects/$projectName/plan_policy'
      preLoaderRoute: typeof OrchestratorReposNamespaceProjectsProjectNamePlan_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/repos/$namespace/projects/$projectName/access_policy': {
      id: '/_orchestrator/repos/$namespace/projects/$projectName/access_policy'
      path: '/repos/$namespace/projects/$projectName/access_policy'
      fullPath: '/repos/$namespace/projects/$projectName/access_policy'
      preLoaderRoute: typeof OrchestratorReposNamespaceProjectsProjectNameAccess_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orchestrator/repos/$namespace/projects/$projectName/jobs/$jobId/set-status': {
      id: '/_orchestrator/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
      path: '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
      fullPath: '/repos/$namespace/projects/$projectName/jobs/$jobId/set-status'
      preLoaderRoute: typeof OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardDashboardConnectionsRouteChildren {
  AuthenticatedDashboardDashboardConnectionsConnectionIdRoute: typeof AuthenticatedDashboardDashboardConnectionsConnectionIdRoute
}

const AuthenticatedDashboardDashboardConnectionsRouteChildren: AuthenticatedDashboardDashboardConnectionsRouteChildren =
  {
    AuthenticatedDashboardDashboardConnectionsConnectionIdRoute:
      AuthenticatedDashboardDashboardConnectionsConnectionIdRoute,
  }

const AuthenticatedDashboardDashboardConnectionsRouteWithChildren =
  AuthenticatedDashboardDashboardConnectionsRoute._addFileChildren(
    AuthenticatedDashboardDashboardConnectionsRouteChildren,
  )

interface AuthenticatedDashboardDashboardProjectsRouteChildren {
  AuthenticatedDashboardDashboardProjectsProjectidRoute: typeof AuthenticatedDashboardDashboardProjectsProjectidRoute
  AuthenticatedDashboardDashboardProjectsIndexRoute: typeof AuthenticatedDashboardDashboardProjectsIndexRoute
}

const AuthenticatedDashboardDashboardProjectsRouteChildren: AuthenticatedDashboardDashboardProjectsRouteChildren =
  {
    AuthenticatedDashboardDashboardProjectsProjectidRoute:
      AuthenticatedDashboardDashboardProjectsProjectidRoute,
    AuthenticatedDashboardDashboardProjectsIndexRoute:
      AuthenticatedDashboardDashboardProjectsIndexRoute,
  }

const AuthenticatedDashboardDashboardProjectsRouteWithChildren =
  AuthenticatedDashboardDashboardProjectsRoute._addFileChildren(
    AuthenticatedDashboardDashboardProjectsRouteChildren,
  )

interface AuthenticatedDashboardDashboardReposRouteChildren {
  AuthenticatedDashboardDashboardReposRepoIdRoute: typeof AuthenticatedDashboardDashboardReposRepoIdRoute
  AuthenticatedDashboardDashboardReposConnectRoute: typeof AuthenticatedDashboardDashboardReposConnectRoute
  AuthenticatedDashboardDashboardReposIndexRoute: typeof AuthenticatedDashboardDashboardReposIndexRoute
}

const AuthenticatedDashboardDashboardReposRouteChildren: AuthenticatedDashboardDashboardReposRouteChildren =
  {
    AuthenticatedDashboardDashboardReposRepoIdRoute:
      AuthenticatedDashboardDashboardReposRepoIdRoute,
    AuthenticatedDashboardDashboardReposConnectRoute:
      AuthenticatedDashboardDashboardReposConnectRoute,
    AuthenticatedDashboardDashboardReposIndexRoute:
      AuthenticatedDashboardDashboardReposIndexRoute,
  }

const AuthenticatedDashboardDashboardReposRouteWithChildren =
  AuthenticatedDashboardDashboardReposRoute._addFileChildren(
    AuthenticatedDashboardDashboardReposRouteChildren,
  )

interface AuthenticatedDashboardDashboardSettingsRouteChildren {
  AuthenticatedDashboardDashboardSettingsTokensRoute: typeof AuthenticatedDashboardDashboardSettingsTokensRoute
  AuthenticatedDashboardDashboardSettingsUserRoute: typeof AuthenticatedDashboardDashboardSettingsUserRoute
}

const AuthenticatedDashboardDashboardSettingsRouteChildren: AuthenticatedDashboardDashboardSettingsRouteChildren =
  {
    AuthenticatedDashboardDashboardSettingsTokensRoute:
      AuthenticatedDashboardDashboardSettingsTokensRoute,
    AuthenticatedDashboardDashboardSettingsUserRoute:
      AuthenticatedDashboardDashboardSettingsUserRoute,
  }

const AuthenticatedDashboardDashboardSettingsRouteWithChildren =
  AuthenticatedDashboardDashboardSettingsRoute._addFileChildren(
    AuthenticatedDashboardDashboardSettingsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDashboardConnectionsRoute: typeof AuthenticatedDashboardDashboardConnectionsRouteWithChildren
  AuthenticatedDashboardDashboardDriftRoute: typeof AuthenticatedDashboardDashboardDriftRoute
  AuthenticatedDashboardDashboardOnboardingRoute: typeof AuthenticatedDashboardDashboardOnboardingRoute
  AuthenticatedDashboardDashboardProjectsRoute: typeof AuthenticatedDashboardDashboardProjectsRouteWithChildren
  AuthenticatedDashboardDashboardReposRoute: typeof AuthenticatedDashboardDashboardReposRouteWithChildren
  AuthenticatedDashboardDashboardSettingsRoute: typeof AuthenticatedDashboardDashboardSettingsRouteWithChildren
  AuthenticatedDashboardDashboardUnitsUnitIdRoute: typeof AuthenticatedDashboardDashboardUnitsUnitIdRoute
  AuthenticatedDashboardDashboardUnitsIndexRoute: typeof AuthenticatedDashboardDashboardUnitsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardConnectionsRoute:
      AuthenticatedDashboardDashboardConnectionsRouteWithChildren,
    AuthenticatedDashboardDashboardDriftRoute:
      AuthenticatedDashboardDashboardDriftRoute,
    AuthenticatedDashboardDashboardOnboardingRoute:
      AuthenticatedDashboardDashboardOnboardingRoute,
    AuthenticatedDashboardDashboardProjectsRoute:
      AuthenticatedDashboardDashboardProjectsRouteWithChildren,
    AuthenticatedDashboardDashboardReposRoute:
      AuthenticatedDashboardDashboardReposRouteWithChildren,
    AuthenticatedDashboardDashboardSettingsRoute:
      AuthenticatedDashboardDashboardSettingsRouteWithChildren,
    AuthenticatedDashboardDashboardUnitsUnitIdRoute:
      AuthenticatedDashboardDashboardUnitsUnitIdRoute,
    AuthenticatedDashboardDashboardUnitsIndexRoute:
      AuthenticatedDashboardDashboardUnitsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  OrchestratorJob_artefactsRoute: OrchestratorJob_artefactsRoute,
  TfeSplatRoute: TfeSplatRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  AppSettingsTokensRoute: AppSettingsTokensRoute,
  OrchestratorGithubCallbackRoute: OrchestratorGithubCallbackRoute,
  OrchestratorGithubWebhookRoute: OrchestratorGithubWebhookRoute,
  OrchestratorOrgsOrgIdAccess_policyRoute:
    OrchestratorOrgsOrgIdAccess_policyRoute,
  OrchestratorOrgsOrgIdPlan_policyRoute: OrchestratorOrgsOrgIdPlan_policyRoute,
  OrchestratorReposNamespaceReportProjectsRoute:
    OrchestratorReposNamespaceReportProjectsRoute,
  ApiAuthWorkosSwitchOrgRoute: ApiAuthWorkosSwitchOrgRoute,
  ApiAuthWorkosWebhooksRoute: ApiAuthWorkosWebhooksRoute,
  OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute:
    OrchestratorReposNamespaceProjectsProjectNameAccess_policyRoute,
  OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute:
    OrchestratorReposNamespaceProjectsProjectNamePlan_policyRoute,
  OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute:
    OrchestratorReposNamespaceProjectsProjectNameJobsJobIdSetStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
