{{- if not .Values.digger.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digger-managed.fullname" . }}-secret
  labels:
    {{- include "digger-managed.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Configuration
  {{- if or .Values.digger.postgres.host .Values.digger.postgres.user .Values.digger.postgres.database }}
  DATABASE_URL: "postgres://{{ .Values.digger.postgres.user }}:{{ .Values.digger.postgres.password }}@{{ .Values.digger.postgres.host }}:{{ .Values.digger.postgres.port }}/{{ .Values.digger.postgres.database }}?sslmode={{ .Values.digger.postgres.sslmode }}"
  {{- end }}

  # Digger Configuration
  {{- if .Values.digger.config.enableApiEndpoints }}
  DIGGER_ENABLE_API_ENDPOINTS: "{{ .Values.digger.config.enableApiEndpoints }}"
  {{- end }}
  {{- if .Values.digger.config.enableInternalEndpoints }}
  DIGGER_ENABLE_INTERNAL_ENDPOINTS: "{{ .Values.digger.config.enableInternalEndpoints }}"
  {{- end }}
  {{- if .Values.digger.config.encryptionSecret }}
  DIGGER_ENCRYPTION_SECRET: {{ .Values.digger.config.encryptionSecret | quote }}
  {{- end }}
  {{- if .Values.digger.config.generationApiToken }}
  DIGGER_GENERATION_API_TOKEN: {{ .Values.digger.config.generationApiToken | quote }}
  {{- end }}
  {{- if .Values.digger.config.generationEndpoint }}
  DIGGER_GENERATION_ENDPOINT: {{ .Values.digger.config.generationEndpoint | quote }}
  {{- end }}
  {{- if .Values.digger.config.internalSecret }}
  DIGGER_INTERNAL_SECRET: {{ .Values.digger.config.internalSecret | quote }}
  {{- end }}
  {{- if .Values.digger.config.licenseKey }}
  DIGGER_LICENSE_KEY: {{ .Values.digger.config.licenseKey | quote }}
  {{- end }}
  DIGGER_LOAD_PROJECTS_ON_PUSH: "{{ .Values.digger.config.loadProjectsOnPush }}"
  DIGGER_LOG_LEVEL: {{ .Values.digger.logLevel | quote }}
  DIGGER_MAX_PROJECTS_PER_CHANGE: "{{ .Values.digger.config.maxProjectsPerChange }}"
  {{- if .Values.digger.config.projectsSvcAppName }}
  DIGGER_PROJECTS_SVC_APP_NAME: {{ .Values.digger.config.projectsSvcAppName | quote }}
  {{- end }}

  # GitHub App Configuration
  {{- if .Values.digger.github.appClientId }}
  GITHUB_APP_CLIENT_ID: {{ .Values.digger.github.appClientId | quote }}
  {{- end }}
  {{- if .Values.digger.github.appClientSecret }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.digger.github.appClientSecret | quote }}
  {{- end }}
  {{- if .Values.digger.github.appId }}
  GITHUB_APP_ID: {{ .Values.digger.github.appId | quote }}
  {{- end }}
  {{- if .Values.digger.github.appPrivateKeyBase64 }}
  GITHUB_APP_PRIVATE_KEY_BASE64: {{ .Values.digger.github.appPrivateKeyBase64 | quote }}
  {{- end }}
  {{- if .Values.digger.github.webhookSecret }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.digger.github.webhookSecret | quote }}
  {{- end }}

  # Go Configuration
  GODEBUG: {{ .Values.digger.godebug | quote }}
  GOFIPS140: {{ .Values.digger.gofips140 | quote }}

  # Application URLs
  {{- if .Values.digger.hostname }}
  HOSTNAME: {{ .Values.digger.hostname | quote }}
  {{- end }}
  JWT_AUTH: "{{ .Values.digger.jwtAuth }}"

  # Optional: Analytics & Monitoring
  {{- if .Values.digger.segmentApiKey }}
  SEGMENT_API_KEY: {{ .Values.digger.segmentApiKey | quote }}
  {{- end }}
  {{- if .Values.digger.sentryDsn }}
  SENTRY_DSN: {{ .Values.digger.sentryDsn | quote }}
  {{- end }}
{{- end }}

