{{- if not .Values.drift.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digger-drift.fullname" . }}-secret
  labels:
    {{- include "digger-drift.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Drift service configuration
  {{- if .Values.drift.config.hostname }}
  DIGGER_HOSTNAME: {{ .Values.drift.config.hostname | quote }}
  {{- end }}
  {{- if .Values.drift.config.webhookSecret }}
  DIGGER_WEBHOOK_SECRET: {{ .Values.drift.config.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.drift.config.appUrl }}
  DIGGER_APP_URL: {{ .Values.drift.config.appUrl | quote }}
  {{- end }}
  {{- if .Values.drift.config.driftReporterHostname }}
  DIGGER_DRIFT_REPORTER_HOSTNAME: {{ .Values.drift.config.driftReporterHostname | quote }}
  {{- end }}
  
  # GitHub configuration
  {{- if .Values.drift.github.org }}
  GITHUB_ORG: {{ .Values.drift.github.org | quote }}
  {{- end }}
  {{- if .Values.drift.github.appID }}
  GITHUB_APP_ID: {{ .Values.drift.github.appID | quote }}
  {{- end }}
  {{- if .Values.drift.github.appClientID }}
  GITHUB_APP_CLIENT_ID: {{ .Values.drift.github.appClientID | quote }}
  {{- end }}
  {{- if .Values.drift.github.appClientSecret }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.drift.github.appClientSecret | quote }}
  {{- end }}
  {{- if .Values.drift.github.appPrivateKey }}
  GITHUB_APP_PRIVATE_KEY_BASE64: {{ .Values.drift.github.appPrivateKey | quote }}
  {{- end }}
  {{- if .Values.drift.github.webhookSecret }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.drift.github.webhookSecret | quote }}
  {{- end }}
{{- end }}

