{{- if not .Values.taco.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taco-statesman.fullname" . }}-secret
  labels:
    {{- include "taco-statesman.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Storage configuration
  {{- if eq .Values.taco.storage.type "s3" }}
  OPENTACO_S3_BUCKET: {{ .Values.taco.storage.s3.bucket | quote }}
  OPENTACO_S3_REGION: {{ .Values.taco.storage.s3.region | quote }}
  {{- if .Values.taco.storage.s3.prefix }}
  OPENTACO_S3_PREFIX: {{ .Values.taco.storage.s3.prefix | quote }}
  {{- end }}
  {{- if .Values.taco.storage.s3.endpoint }}
  AWS_ENDPOINT: {{ .Values.taco.storage.s3.endpoint | quote }}
  {{- end }}
  {{- if .Values.taco.storage.s3.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.taco.storage.s3.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.taco.storage.s3.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.taco.storage.s3.secretAccessKey | quote }}
  {{- end }}
  {{- if .Values.taco.storage.s3.awsRegion }}
  AWS_REGION: {{ .Values.taco.storage.s3.awsRegion | quote }}
  {{- end }}
  {{- end }}
  
  # Auth configuration
  {{- if not .Values.taco.auth.disable }}
  {{- if .Values.taco.auth.issuer }}
  OPENTACO_AUTH_ISSUER: {{ .Values.taco.auth.issuer | quote }}
  {{- end }}
  {{- if .Values.taco.auth.clientId }}
  OPENTACO_AUTH_CLIENT_ID: {{ .Values.taco.auth.clientId | quote }}
  {{- end }}
  {{- if .Values.taco.auth.clientSecret }}
  OPENTACO_AUTH_CLIENT_SECRET: {{ .Values.taco.auth.clientSecret | quote }}
  {{- end }}
  {{- if .Values.taco.auth.authUrl }}
  OPENTACO_AUTH_AUTH_URL: {{ .Values.taco.auth.authUrl | quote }}
  {{- end }}
  {{- if .Values.taco.auth.tokenUrl }}
  OPENTACO_AUTH_TOKEN_URL: {{ .Values.taco.auth.tokenUrl | quote }}
  {{- end }}
  {{- end }}
  
  # Internal API configuration
  {{- if .Values.taco.enableInternalEndpoints }}
  OPENTACO_ENABLE_INTERNAL_ENDPOINTS: {{ .Values.taco.internalSecret | quote }}
  {{- end }}
  
  # PostgreSQL configuration
  {{- if .Values.taco.postgres.host }}
  OPENTACO_POSTGRES_HOST: {{ .Values.taco.postgres.host | quote }}
  {{- end }}
  {{- if .Values.taco.postgres.port }}
  OPENTACO_POSTGRES_PORT: {{ .Values.taco.postgres.port | quote }}
  {{- end }}
  {{- if .Values.taco.postgres.user }}
  OPENTACO_POSTGRES_USER: {{ .Values.taco.postgres.user | quote }}
  {{- end }}
  {{- if .Values.taco.postgres.database }}
  OPENTACO_POSTGRES_DBNAME: {{ .Values.taco.postgres.database | quote }}
  {{- end }}
  {{- if .Values.taco.postgres.queryBackend }}
  OPENTACO_QUERY_BACKEND: {{ .Values.taco.postgres.queryBackend | quote }}
  {{- end }}
  {{- if and (not .Values.taco.postgres.existingSecretName) .Values.taco.postgres.password }}
  OPENTACO_POSTGRES_PASSWORD: {{ .Values.taco.postgres.password | quote }}
  {{- end }}
{{- end }}

