{{- if not .Values.sidecar.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taco-sidecar.fullname" . }}-secrets
  labels:
    {{- include "taco-sidecar.labels" . | nindent 4 }}
type: Opaque
stringData:
  SANDBOX_RUNNER: {{ .Values.sidecar.secret.sandboxRunner | quote }}
  E2B_API_KEY: {{ .Values.sidecar.secret.e2bApiKey | quote }}
  E2B_BAREBONES_TEMPLATE_ID: {{ .Values.sidecar.secret.e2bBareBonesTemplateId | quote }}
{{- end }}
