apiVersion: v1
kind: Service
metadata:
  name: {{ include "taco-sidecar.fullname" . }}
  labels:
    {{- include "taco-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sidecar.service.type }}
  ports:
    - port: {{ .Values.sidecar.service.port }}
      targetPort: {{ .Values.sidecar.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "taco-sidecar.selectorLabels" . | nindent 4 }}
