{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "digger-backend.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "{{ include "digger-backend.fullname" . }}-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "digger-backend.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "digger-backend.name" . }}-postgres
    spec:
      containers:
      - name: postgres
        image: "postgres:alpine"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              {{- if .Values.postgres.secret.useExistingSecret }}
              name: {{ .Values.postgres.secret.existingSecretName }}
              {{- else }}
              name: {{ include "digger-backend.fullname" . }}-postgres-secret
              {{- end }}
{{- end }}
