// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountDeleteToken = "account_delete_tokens"

// AccountDeleteToken mapped from table <account_delete_tokens>
type AccountDeleteToken struct {
	Token  string `gorm:"column:token;not null;default:uuid_generate_v4()" json:"token"`
	UserID string `gorm:"column:user_id;primaryKey" json:"user_id"`
}

// TableName AccountDeleteToken's table name
func (*AccountDeleteToken) TableName() string {
	return TableNameAccountDeleteToken
}
