// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiggerRunStage = "digger_run_stages"

// DiggerRunStage mapped from table <digger_run_stages>
type DiggerRunStage struct {
	ID        string         `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	BatchID   string         `gorm:"column:batch_id;not null" json:"batch_id"`
}

// TableName DiggerRunStage's table name
func (*DiggerRunStage) TableName() string {
	return TableNameDiggerRunStage
}
