// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDiggerBatch = "digger_batches"

// DiggerBatch mapped from table <digger_batches>
type DiggerBatch struct {
	ID                   string  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	PrNumber             int64   `gorm:"column:pr_number" json:"pr_number"`
	Status               int16   `gorm:"column:status;not null" json:"status"`
	BranchName           string  `gorm:"column:branch_name;not null" json:"branch_name"`
	DiggerConfig         string  `gorm:"column:digger_config" json:"digger_config"`
	GithubInstallationID int64   `gorm:"column:github_installation_id" json:"github_installation_id"`
	RepoFullName         string  `gorm:"column:repo_full_name;not null" json:"repo_full_name"`
	RepoOwner            string  `gorm:"column:repo_owner;not null" json:"repo_owner"`
	RepoName             string  `gorm:"column:repo_name;not null" json:"repo_name"`
	BatchType            string  `gorm:"column:batch_type;not null" json:"batch_type"`
	CommentID            int64   `gorm:"column:comment_id" json:"comment_id"`
	SourceDetails        []uint8 `gorm:"column:source_details" json:"source_details"`
	Vcs                  string  `gorm:"column:vcs" json:"vcs"`
	GitlabProjectID      int64   `gorm:"column:gitlab_project_id" json:"gitlab_project_id"`
	OrganizationID       string  `gorm:"column:organization_id" json:"organization_id"`
	EventType            string  `gorm:"column:event_type" json:"event_type"`
}

// TableName DiggerBatch's table name
func (*DiggerBatch) TableName() string {
	return TableNameDiggerBatch
}
