// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiggerJobToken = "digger_job_tokens"

// DiggerJobToken mapped from table <digger_job_tokens>
type DiggerJobToken struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Value          string         `gorm:"column:value" json:"value"`
	Expiry         time.Time      `gorm:"column:expiry" json:"expiry"`
	Type           string         `gorm:"column:type" json:"type"`
	OrganisationID string         `gorm:"column:organisation_id" json:"organisation_id"`
}

// TableName DiggerJobToken's table name
func (*DiggerJobToken) TableName() string {
	return TableNameDiggerJobToken
}
