// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGithubAppInstallationLink = "github_app_installation_links"

// GithubAppInstallationLink mapped from table <github_app_installation_links>
type GithubAppInstallationLink struct {
	ID                   string         `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt            time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	GithubInstallationID int64          `gorm:"column:github_installation_id;not null" json:"github_installation_id"`
	OrganizationID       string         `gorm:"column:organization_id;not null" json:"organization_id"`
	Status               int16          `gorm:"column:status;not null" json:"status"`
}

// TableName GithubAppInstallationLink's table name
func (*GithubAppInstallationLink) TableName() string {
	return TableNameGithubAppInstallationLink
}
