// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInternalFeedbackComment = "internal_feedback_comments"

// InternalFeedbackComment mapped from table <internal_feedback_comments>
type InternalFeedbackComment struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	ThreadID  string    `gorm:"column:thread_id;not null" json:"thread_id"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName InternalFeedbackComment's table name
func (*InternalFeedbackComment) TableName() string {
	return TableNameInternalFeedbackComment
}
