// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInternalBlogPostTagsRelationship = "internal_blog_post_tags_relationship"

// InternalBlogPostTagsRelationship mapped from table <internal_blog_post_tags_relationship>
type InternalBlogPostTagsRelationship struct {
	BlogPostID string `gorm:"column:blog_post_id;primaryKey" json:"blog_post_id"`
	TagID      int32  `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName InternalBlogPostTagsRelationship's table name
func (*InternalBlogPostTagsRelationship) TableName() string {
	return TableNameInternalBlogPostTagsRelationship
}
