// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInternalBlogAuthorProfile = "internal_blog_author_profiles"

// InternalBlogAuthorProfile mapped from table <internal_blog_author_profiles>
type InternalBlogAuthorProfile struct {
	UserID          string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	DisplayName     string    `gorm:"column:display_name;not null" json:"display_name"`
	Bio             string    `gorm:"column:bio;not null" json:"bio"`
	AvatarURL       string    `gorm:"column:avatar_url;not null" json:"avatar_url"`
	WebsiteURL      string    `gorm:"column:website_url" json:"website_url"`
	TwitterHandle   string    `gorm:"column:twitter_handle" json:"twitter_handle"`
	FacebookHandle  string    `gorm:"column:facebook_handle" json:"facebook_handle"`
	LinkedinHandle  string    `gorm:"column:linkedin_handle" json:"linkedin_handle"`
	InstagramHandle string    `gorm:"column:instagram_handle" json:"instagram_handle"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName InternalBlogAuthorProfile's table name
func (*InternalBlogAuthorProfile) TableName() string {
	return TableNameInternalBlogAuthorProfile
}
