// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInternalBlogPostTag = "internal_blog_post_tags"

// InternalBlogPostTag mapped from table <internal_blog_post_tags>
type InternalBlogPostTag struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Slug        string `gorm:"column:slug;not null" json:"slug"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName InternalBlogPostTag's table name
func (*InternalBlogPostTag) TableName() string {
	return TableNameInternalBlogPostTag
}
