// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationCredit = "organization_credits"

// OrganizationCredit mapped from table <organization_credits>
type OrganizationCredit struct {
	OrganizationID string `gorm:"column:organization_id;primaryKey" json:"organization_id"`
	Credits        int64  `gorm:"column:credits;not null;default:12" json:"credits"`
}

// TableName OrganizationCredit's table name
func (*OrganizationCredit) TableName() string {
	return TableNameOrganizationCredit
}
