// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganizationMember = "organization_members"

// OrganizationMember mapped from table <organization_members>
type OrganizationMember struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	MemberID       string    `gorm:"column:member_id;not null" json:"member_id"`
	MemberRole     string    `gorm:"column:member_role;not null" json:"member_role"`
	OrganizationID string    `gorm:"column:organization_id;not null" json:"organization_id"`
}

// TableName OrganizationMember's table name
func (*OrganizationMember) TableName() string {
	return TableNameOrganizationMember
}
