// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	ID        string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Title     string    `gorm:"column:title;not null;default:Test Organization" json:"title"`
	Slug      string    `gorm:"column:slug;not null;default:(gen_random_uuid())" json:"slug"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
