// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProjectRun = "project_runs"

// ProjectRun mapped from table <project_runs>
type ProjectRun struct {
	ID            string         `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ProjectID     string         `gorm:"column:project_id" json:"project_id"`
	StartedAt     int64          `gorm:"column:started_at" json:"started_at"`
	EndedAt       int64          `gorm:"column:ended_at" json:"ended_at"`
	Status        string         `gorm:"column:status" json:"status"`
	Command       string         `gorm:"column:command" json:"command"`
	Output        string         `gorm:"column:output" json:"output"`
	ActorUsername string         `gorm:"column:actor_username" json:"actor_username"`
}

// TableName ProjectRun's table name
func (*ProjectRun) TableName() string {
	return TableNameProjectRun
}
