// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID string `gorm:"column:user_id;not null" json:"user_id"`
	Role   string `gorm:"column:role;not null" json:"role"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
