// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPrivateInfo = "user_private_info"

// UserPrivateInfo mapped from table <user_private_info>
type UserPrivateInfo struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt           time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	DefaultOrganization string    `gorm:"column:default_organization" json:"default_organization"`
}

// TableName UserPrivateInfo's table name
func (*UserPrivateInfo) TableName() string {
	return TableNameUserPrivateInfo
}
