// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserM2mApplication = "user_m2m_applications"

// UserM2mApplication mapped from table <user_m2m_applications>
type UserM2mApplication struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientID    string    `gorm:"column:clientId;not null" json:"clientId"`
	Name        string    `gorm:"column:name" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Audience    string    `gorm:"column:audience;not null" json:"audience"`
	Issuer      string    `gorm:"column:issuer;not null" json:"issuer"`
}

// TableName UserM2mApplication's table name
func (*UserM2mApplication) TableName() string {
	return TableNameUserM2mApplication
}
