// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserOnboarding = "user_onboarding"

// UserOnboarding mapped from table <user_onboarding>
type UserOnboarding struct {
	UserID        string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	AcceptedTerms bool      `gorm:"column:accepted_terms;not null" json:"accepted_terms"`
}

// TableName UserOnboarding's table name
func (*UserOnboarding) TableName() string {
	return TableNameUserOnboarding
}
