---
name: Backend Go Tests

"on":
  push:
    branches: ['develop']
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test that the docker image still builds successfully
        uses: depot/setup-action@v1
      
      - name: Build Docker image with Depot
        uses: depot/build-push-action@v1
        with:
          project: f11hp4hlmg
          context: .
          file: ./Dockerfile_backend
          push: false
          build-args: |
            COMMIT_SHA=${{ github.sha }}

      - name: Deps
        run: go get -v ./...
        working-directory: backend

      - name: Build
        run: go build
        working-directory: backend

      - name: Test
        run: |
          go test ./...
        env:
          GITHUB_PAT_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        working-directory: backend
