---
name: EE Backend Publish docker image

"on":
  release:
    types:
      - 'released'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_backend_ee_fips

jobs:
  build-and-push-image:
    if: (startswith(github.event.release.tag_name, 'v'))

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: "Dockerfile_backend_ee"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GODEBUG_VALUE=fips140=only
            GOFIPS140_VALUE=v1.0.0            
            
