name: Go
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Deps
        run: go get -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...