name: Go
on: [ push, pull_request ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Deps
        run: go get -v ./...

      - name: Build
        run: go build -v ./cmd/digger

      - name: Install Azurite
        run: npm install -g azurite

      - name: Start Azurite service
        run: azurite --silent &

      - name: Test
        run: go test -v ./...