name: Go
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
        id: go

      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Deps
        run: go get -v ./...

      - name: Build
        run: go build -v ./cmd/digger

      - name: Install Azurite
        run: npm install -g azurite

      - name: Start Azurite service
        run: azurite --silent &

      - name: Test
        run: go test -v ./...